// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProbeVideo(arg1) {
  return window['go']['main']['App']['ProbeVideo'](arg1);
}

export function ProcessBoomerang(arg1, arg2) {
  return window['go']['main']['App']['ProcessBoomerang'](arg1, arg2);
}

export function ProcessCut(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessCut'](arg1, arg2, arg3);
}

export function ProcessJoin(arg1, arg2) {
  return window['go']['main']['App']['ProcessJoin'](arg1, arg2);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}

export function SaveTemp(arg1, arg2) {
  return window['go']['main']['App']['SaveTemp'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
