// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFile(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ProbeVideo(arg1:string):Promise<main.VideoMetadata>;

export function ProcessBoomerang(arg1:string,arg2:number):Promise<string>;

export function ProcessCut(arg1:string,arg2:number,arg3:number):Promise<string>;

export function ProcessJoin(arg1:string,arg2:string):Promise<string>;

export function SaveFileAs(arg1:string):Promise<string>;

export function SaveTemp(arg1:Array<number>,arg2:string):Promise<string>;

export function SelectFile():Promise<string>;
